# -*- coding: utf-8 -*-
"""Face Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yHB9kE_l4_BEwAk10A84Wrn7--x_BLF9

Training
"""

import os
import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow

p=[]
DIR='/content/drive/MyDrive/OpenCV/Faces/train'
for i in os.listdir(DIR):
  p.append(i)

haar_cascade=cv.CascadeClassifier('/content/drive/MyDrive/OpenCV/haar_face.xml')

features=[]
labels=[]

def create_train():
  for person in p:
    path=os.path.join(DIR,person)
    label=p.index(person)

    for img in os.listdir(path):
      img_path=os.path.join(path,img)

      img_array=cv.imread(img_path)
      gray=cv.cvtColor(img_array,cv.COLOR_BGR2GRAY)

      faces_rect=haar_cascade.detectMultiScale(gray,scaleFactor=1.1,minNeighbors=3)

      for (x,y,w,h) in faces_rect:
        faces_roi=gray[y:y+h,x:x+w]
        features.append(faces_roi)
        labels.append(label)

create_train()

print(f'Length of the features={len(features)}')
print(f'Length of the labels={len(labels)}')

features=np.array(features,dtype='object')
labels=np.array(labels)

face_recognizer=cv.face.LBPHFaceRecognizer_create()
face_recognizer.train(features,labels)
face_recognizer.save('face_trained.yml')

np.save('features.npy',features)
np.save('lables.npy',labels)

"""Test"""
